### ISSUE TITLE
How to handle errors

### ISSUE THREAD

**Issue by grandeljay** [qferr/mjml-php#11]
Hello,

I feel bad for asking but how do I handle errors?

```php
$renderer = new \Qferrer\Mjml\Renderer\ApiRenderer( $api_key, $api_secret );
$html     = $renderer->render( file_get_contents( '../templates/default.mjml' ) );
```

I deliberately entered wrong credentials and received a fatal PHP error.

Do I just try/catch the renderer or is there a different or more proper way of getting the response/error?

**Comment by qferr** [comment]
Hello,

Could you share the fatal error message?

From the MJML Api documentation, the API returns a `403 Forbidden` response for wrong credentials and Guzzle throws the `GuzzleHttp\Exception\ClientException` exception for 400 level errors, so you should use a try/catch with this exception.

Best regards,

Quentin

**Comment by grandeljay** [comment]
Hey Quentin,

<details>
<summary>here is the full error I got</summary>

```log
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://api.mjml.io/v1/render` resulted in a `401 Unauthorized` response:
{"message":"Authentication required","request_id":"ee333f26-1f99-46ce-a7cc-35e1577c1ce9","started_at":"2022-01-13T07:07: (truncated...)
 in /path/to/wp\wp-content\plugins\my-plugin\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113
Stack trace:
#0 /path/to/wp\wp-content\plugins\my-plugin\vendor\guzzlehttp\guzzle\src\Middleware.php(69): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), NULL, Array, NULL)
#1 /path/to/wp\wp-content\plugins\my-plugin\vendor\guzzlehttp\promises\src\Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /path/to/wp\wp-content\plugins\my-plugin\vendor\guzzlehttp\promises\src\Promise.php(153): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL)
#3 /path/to/wp\wp-content\plugins\my-plugin\vendor\guzzlehttp\promises\src\TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /path/to/wp\wp-content\plugins\my-plugin\vendor\guzzlehttp\promises\src\Promise.php(248): GuzzleHttp\Promise\TaskQueue->run(true)
#5 /path/to/wp\wp-content\plugins\my-plugin\vendor\guzzlehttp\promises\src\Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /path/to/wp\wp-content\plugins\my-plugin\vendor\guzzlehttp\promises\src\Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /path/to/wp\wp-content\plugins\my-plugin\vendor\guzzlehttp\promises\src\Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /path/to/wp\wp-content\plugins\my-plugin\vendor\guzzlehttp\promises\src\Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /path/to/wp\wp-content\plugins\my-plugin\vendor\guzzlehttp\guzzle\src\Client.php(187): GuzzleHttp\Promise\Promise->wait()
#10 /path/to/wp\wp-content\plugins\my-plugin\vendor\guzzlehttp\guzzle\src\ClientTrait.php(95): GuzzleHttp\Client->request('POST', 'render', Array)
#11 /path/to/wp\wp-content\plugins\my-plugin\vendor\qferr\mjml-php\src\Mjml\Renderer\ApiRenderer.php(61): GuzzleHttp\Client->post('render', Array)
#12 /path/to/wp\wp-content\plugins\my-plugin\inc\ajax\mjml.php(253): Qferrer\Mjml\Renderer\ApiRenderer->render('<mjml>\n<mj-head...')
#13 /path/to/wp\wp-includes\class-wp-hook.php(303): hsn_ajax_mjml('')
#14 /path/to/wp\wp-includes\class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#15 /path/to/wp\wp-includes\plugin.php(470): WP_Hook->do_action(Array)
#16 /path/to/wp\wp-admin\admin-ajax.php(187): do_action('wp_ajax_mjml')
#17 {main}
  thrown in /path/to/wp\wp-content\plugins\my-plugin\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113
```

</details>

> you should use a try/catch with this exception.

Thanks, for the info, I will keep doing this then. I was just wondering if it was better for this library to return the error back as a message instead of throwing an error to avoid disruptions?

Best
Jay
